/**
 * Lists assets/music/* and either prints JSON or writes js/music-catalog.generated.js.
 *
 *   node tools/scan-music.mjs           # stdout only (paste / inspect)
 *   node tools/scan-music.mjs --write   # update generated catalog (commit the file)
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const musicDir = path.join(root, 'assets', 'music');
const outFile = path.join(root, 'js', 'music-catalog.generated.js');

const writeFlag = process.argv.includes('--write');

if (!fs.existsSync(musicDir)) {
    console.error('Missing folder:', musicDir);
    process.exit(1);
}

const files = fs.readdirSync(musicDir).filter((f) =>
    /\.(mp3|m4a|aac|wav|ogg|flac)$/i.test(f)
);
files.sort();

const today = new Date().toISOString().slice(0, 10);

const rows = files.map((f) => {
    const ext = path.extname(f).slice(1).toLowerCase();
    const base = f.replace(/\.[^.]+$/, '');
    return {
        src: 'assets/music/' + f,
        title: base.replace(/[_-]+/g, ' ').trim(),
        artist: 'Natee',
        duration: '',
        format: ext,
        added: today
    };
});

const banner = '// AUTO-GENERATED by: node tools/scan-music.mjs --write\n'
    + '// Do not edit by hand — re-run after adding/removing files in assets/music/\n\n';

if (writeFlag) {
    const body = banner + 'window.__MUSIC_CATALOG_SCAN = ' + JSON.stringify(rows, null, 2) + ';\n';
    fs.writeFileSync(outFile, body, 'utf8');
    console.log('Wrote', outFile, '(' + rows.length + ' tracks)');
} else {
    console.log('// Paste into overrides or run with --write to refresh js/music-catalog.generated.js\n');
    console.log(JSON.stringify(rows, null, 4));
}
